# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

task :plugins do
  `rm -rf vendor/plugins/rspec`
  `script/plugin install svn://rubyforge.org/var/svn/rspec/tags/REL_0_7_3/vendor/rspec_on_rails/vendor/plugins/rspec`
end
